const style = {
  wrapper: {
    display: "flex",
    gap: "10px",
    width: "100%",
    flexWrap: "wrap",
    alignItems: "center",
    boxSizing: "border-box",
    padding: "0.5rem 0 0.5rem 0",
    justifyContent: "center",
    background: "#f7f7f7",
    borderRadius: "0 0 18px 18px",
    marginTop: "auto",
  },
  inputWrapper: {
    position: "relative",
    flex: 1,
    minWidth: "0",
    maxWidth: "70%",
  },
  attach: {
    width: "20px",
    height: "20px",
    position: "absolute",
    top: "15px",
    right: 0,
  },
  pointer: { cursor: "pointer" },
  w20: {
    width: "20px",
  },
  input: {
    flex: 1,
    height: "40px",
    borderRadius: "5px",
    fontSize: "16px",
    width: "100%",
    minWidth: 0,
    boxSizing: "border-box",
  },
  button: (disabled: boolean)=> ({
    cursor: disabled ? 'not-allowed' : 'pointer',
    color: "black",
    padding: "10px 20px",
    borderRadius: "10px",
    fontSize: "16px",
    minWidth: "120px",
    marginTop: "0.5rem",
    border: "1px solid #ccc",
    background: disabled ? "#eee" : "#fff",
    transition: "background 0.2s, color 0.2s",
  }),
};
export default style;
